export {
  Title,
  Tip,
  shallowIntl,
  createIntl,
  intl,
  createSetterContent,
  obx,
  untracked,
  computed,
  observer,
  globalLocale,
  globalContext,
  makeObservable,
} from '@alilc/lowcode-editor-core';