export default {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: '生态资源',
      href: 'https://github.com/lowcode-workspace/awesome-lowcode-engine',
    },
  ],
};
